FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY . .

# Install PM2 globally
RUN npm install pm2 -g

# Create a non-root user for improved container security
RUN addgroup -S app && adduser -S app -G app
RUN chown -R app:app /app
USER app

EXPOSE 5000

CMD ["pm2-runtime", "server.js"]
